# Generated by Django 3.2.12 on 2022-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='pics')),
                ('teamname', models.CharField(max_length=250)),
                ('teamdesc', models.TextField()),
            ],
        ),
    ]
